
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 01 15:17:27 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 3;
  public static final int INTEGER = 2;
  public static final int NOTEQUAL = 31;
  public static final int GREATER = 32;
  public static final int SEMI = 13;
  public static final int LESS = 28;
  public static final int MINUS = 8;
  public static final int WRITE = 5;
  public static final int AND = 21;
  public static final int INTCONST = 16;
  public static final int OR = 22;
  public static final int BOOL = 24;
  public static final int COMMA = 14;
  public static final int DIV = 7;
  public static final int PLUS = 6;
  public static final int IF = 35;
  public static final int ASSIGN = 12;
  public static final int LESSEQ = 29;
  public static final int MAIN = 25;
  public static final int ID = 15;
  public static final int EOF = 0;
  public static final int RETURN = 34;
  public static final int RIGHTCURLY = 27;
  public static final int error = 1;
  public static final int MUL = 9;
  public static final int EQEQ = 30;
  public static final int LEFTCURLY = 26;
  public static final int REAL = 20;
  public static final int RIGHTPAR = 11;
  public static final int READ = 4;
  public static final int CHARCONST = 17;
  public static final int WHILE = 23;
  public static final int LEFTPAR = 10;
  public static final int REALCONST = 19;
  public static final int THEN = 36;
  public static final int BOOLCONST = 18;
  public static final int GREATEREQ = 33;
}

